# Generated by Django 4.2.11 on 2024-07-11 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('nomortelephone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DistribusiModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_masuk', models.DateField()),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sumber', models.CharField(choices=[('utama', 'Rekening Utama'), ('lainnya', 'Rekening Lainnya')], max_length=50)),
                ('status', models.CharField(choices=[('transfer', 'Transfer'), ('cash', 'Cash')], max_length=50)),
                ('keperluan_bulan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MasterBelanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SSH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uraian', models.TextField()),
                ('satuan', models.CharField(choices=[('bulan', 'Bulan'), ('box', 'Box'), ('paket', 'Paket'), ('buah', 'Buah'), ('kali', 'Kali')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiAnggaranBelanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_anggaran', models.DateField()),
                ('store', models.CharField(max_length=255)),
                ('keterangan', models.TextField()),
                ('jumlah_anggaran', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiBelanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_belanja', models.DateField()),
                ('store', models.CharField(max_length=100)),
                ('upload_bukti', models.FileField(upload_to='bukti/')),
                ('keterangan', models.TextField()),
                ('urai_belanja', models.TextField()),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('realisasi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sisa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kode_belanja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.masterbelanja')),
                ('kode_transaksi_belanja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi_realisasi', to='master.transaksianggaranbelanja')),
            ],
        ),
        migrations.CreateModel(
            name='RencanaAnggaranBelanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_keperluan', models.CharField(max_length=200)),
                ('tgl_mulai', models.DateField()),
                ('tgl_berakhir', models.DateField()),
                ('deskripsi', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MasterPendapatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('tgl_pendapatan', models.DateField()),
                ('kode_pendapatan', models.CharField(max_length=100)),
                ('urai_pendapatan', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('nilai_uang', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bulan', models.IntegerField()),
                ('bukti', models.FileField(upload_to='bukti/')),
                ('keterangan', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Anggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anggaran', models.DecimalField(decimal_places=2, max_digits=12)),
                ('belanja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.masterbelanja')),
                ('rencana_anggaran_belanja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.rencanaanggaranbelanja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
