# Generated by Django 4.2.11 on 2024-07-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kode_belanja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.masterbelanja')),
                ('transaksi_anggaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barang_set', to='master.transaksianggaranbelanja')),
            ],
        ),
    ]
