# Generated by Django 4.2.11 on 2024-07-17 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_barang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksibelanja',
            name='jumlah',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('store', models.CharField(max_length=255)),
                ('keterangan', models.TextField()),
                ('jumlah_realisasi', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('selisih', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jumlah_anggaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.transaksianggaranbelanja')),
            ],
        ),
    ]
